---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: livecode-stg
  labels:
    app: backend
spec:
  ports:
    - port: 3001
      targetPort: 3001
      protocol: TCP
      name: api-port
  selector:
    app: backend