---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: PLACE_HOLDER_NAMESPACE
  labels:
    app: frontend
spec:
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http-port
  selector:
    app: frontend