apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend
  namespace: livecode-stg
  labels:
    app: backend
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-dns01"
    kubernetes.io/ingress.class: "nginx-external"
spec:
  rules:
    - host: api.chat.stg.totvs-livecode.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
                service:
                  name: backend
                  port: 
                    number: 3001
  tls:
    - hosts:
      - api.chat.stg.totvs-livecode.com
      secretName: api.chat.stg.totvs-livecode.com-tls