apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend
  namespace: PLACE_HOLDER_NAMESPACE
  labels:
    app: frontend
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-dns01"
    kubernetes.io/ingress.class: "nginx-external"
spec:
  rules:
    - host: chatPLACE_HOLDER_DOMAIN
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
                service:
                  name: frontend
                  port: 
                    number: 3000
  tls:
    - hosts:
      - chatPLACE_HOLDER_DOMAIN
      secretName: chatPLACE_HOLDER_DOMAIN-tls