---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: PLACE_HOLDER_NAMESPACE
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - image: marcusvmesquita/chat-livecode-backend:PLACE_HOLDER_BACKEND_TAG
          name: chat-livecode-backend
          resources:
            requests:
              memory: 256Mi
              cpu: 500m
            limits:
              memory: 512Mi
              cpu: 1000m
          env: 
            - name: PORT
              value: "3001"
          ports:
            - containerPort: 3001
              name: api-port